# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interest', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=5)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.DepartmentModel')),
            ],
        ),
    ]
