# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
